### ISSUE TITLE
The state file does not correspond to the given data file when using custom feature extraction method

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#1055]
### Discussed in https://github.com/asreview/asreview/discussions/1048

<div type='discussions-op-text'>

<sup>Originally posted by **michagast** April 29, 2022</sup>
Hi everyone,

I am back again this time with a question about asreview lab. I have currently made my own extension for feature extraction for asreview. This can be found [here](https://github.com/michagast/asreview/blob/main/asreviewcontrib/models/enron_fe.py).
The relevant code is as follows:
```

from asreview.models.feature_extraction.base import BaseFeatureExtraction
import numpy as np

import pandas as pd                 #For data science purposes
import re                           #For performing regex
import torch                        #For running models with cuda
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

class Enron(BaseFeatureExtraction):
    """Custom feature extraction

    Feature extraction that generates features based on sentiment values and named entity recogntion among other things.
    """

    name = "enron"
    label = "Enron feature extraction"

    def __init__(self, *args, **kwargs):

        super(Enron, self).__init__(*args, **kwargs)
    def transform(self, texts):
        model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

        tokenizernlp = AutoTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")
        sentiment_analysis = pipeline("sentiment-analysis", model=model, tokenizer=tokenizernlp,
                                           max_length=512,
                                           truncation=True, device=0)
        result = np.empty([0])
        for text in texts:
            np.append(result, sentiment_analysis(text))
        return result
```
 The feature extraction method properly shows up within asreview lab and can be selected. The program then takes a while to apply the feature extraction to the dataset but after a while it gives the following error:
```
ERROR:root:Project enron - ValueError: The state file does not correspond to the given data file, please use another state file or dataset.
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\asreview\__main__.py", line 122, in <module>
    main()
  File "C:AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\asreview\__main__.py", line 80, in main
    entry.load()().execute(sys.argv[2:])
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\asreview\entry_points\lab.py", line 112, in execute
    main_run_model(argv)
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\asreview\webapp\run_model.py", line 200, in main
    raise err
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\asreview\webapp\run_model.py", line 186, in main
    train_model(args.project_id, args.label_method)
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\asreview\webapp\run_model.py", line 117, in train_model
    reviewer = get_reviewer(dataset=data_fp, mode="minimal", **asr_kwargs)
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\asreview\review\factory.py", line 243, in get_reviewer
    reviewer = MinimalReview(as_data,
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\asreview\review\minimal.py", line 21, in __init__
    super(MinimalReview, self).__init__(*args, **kwargs)
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\asreview\review\base.py", line 209, in __init__
    raise ValueError("The state file does not correspond to the "
ValueError: The state file does not correspond to the given data file, please use another state file or dataset.
ERROR:root:Error on training.
```
Long story short, apparently the state file doesn't correspond to the given datafile. However this seems weird as this happens after I have selected the configuration and have asked asreview to train a base model with the given configurations and have thus not changed the dataset in any way. Note that it takes a while for this error to be generated as it seems that feature extraction is working but then suddenly it throws the error. After the error it is not possible to continue to the active learning.

Does anybody have a clue as to what causes this error? Please let me know. 

Thanks in advance,
Micha</div>

**Comment by J535D165** [comment]
Potential issue. I'm transferring it to the issue tracker to be sure it's not missed.

**Comment by PeterLombaers** [comment]
I think the error is in the definition of the transform method, not really in what happens after that.  But it might be useful to have a better error message. Maybe a check to see if the number of rows is correct, directly after feature_extractor.transform() is called.

**Comment by J535D165** [comment]
Thanks for the info @PeterLombaers. Can you review my PR on this?
