### ISSUE TITLE
Not possible to read RIS files from remote location/URL

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#1232]
```python
>>> from asreview import ASReviewData
>>> d = ASReviewData.from_file("https://raw.githubusercontent.com/asreview/systematic-review-datasets/master/datasets/Appenzeller-Herzog_2020/output/Appenzeller-Herzog_2020.csv")
>>> d.df
                                                       title  ... duplicate_record_id
record_id                                                     ...                    
0          Binding Selectivity of Methanobactin from Meth...  ...                 NaN
1          Characteristics and prevalence of Wilson's dis...  ...                 NaN
2          Modality of treatment and potential outcome of...  ...                 NaN
3          The early history of manganese and the recogni...  ...                 NaN
4          Zinc monotherapy for young children with presy...  ...                 NaN
...                                                      ...  ...                 ...
3448       Dietary copper intake in artificially fed infants  ...                 NaN
3449       WTX101 in patients newly diagnosed with Wilson...  ...              3403.0
3450       A two-center randomized controlled feasibility...  ...                 NaN
3451       Zinc-carnosine and vitamin E supplementation d...  ...                 NaN
3452       A clinical study of bone mesenchymal stem cell...  ...                69.0

[3453 rows x 10 columns]
>>> d_ris = ASReviewData.from_file("https://raw.githubusercontent.com/asreview/systematic-review-datasets/master/datasets/van_de_Schoot_2017/raw/schoot-lgmm-ptsd-included-3.ris")
WARNING:root:[Errno 2] No such file or directory: 'https://raw.githubusercontent.com/asreview/systematic-review-datasets/master/datasets/van_de_Schoot_2017/raw/schoot-lgmm-ptsd-included-3.ris'
WARNING:root:[Errno 2] No such file or directory: 'https://raw.githubusercontent.com/asreview/systematic-review-datasets/master/datasets/van_de_Schoot_2017/raw/schoot-lgmm-ptsd-included-3.ris'
WARNING:root:[Errno 2] No such file or directory: 'https://raw.githubusercontent.com/asreview/systematic-review-datasets/master/datasets/van_de_Schoot_2017/raw/schoot-lgmm-ptsd-included-3.ris'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Bruin056/Documents/GitHub/asreview/asreview/data/base.py", line 187, in from_file
    df, column_spec = reader.read_data(fp)
  File "/Users/Bruin056/Documents/GitHub/asreview/asreview/io/ris_reader.py", line 140, in read_data
    raise ValueError("Cannot find proper encoding for data file.")
ValueError: Cannot find proper encoding for data file.
```

```python
>>> from asreview import load_data
>>> d_ris = load_data("https://raw.githubusercontent.com/asreview/systematic-review-datasets/master/datasets/van_de_Schoot_2017/raw/schoot-lgmm-ptsd-included-3.ris")
WARNING:root:[Errno 2] No such file or directory: 'https://raw.githubusercontent.com/asreview/systematic-review-datasets/master/datasets/van_de_Schoot_2017/raw/schoot-lgmm-ptsd-included-3.ris'
WARNING:root:[Errno 2] No such file or directory: 'https://raw.githubusercontent.com/asreview/systematic-review-datasets/master/datasets/van_de_Schoot_2017/raw/schoot-lgmm-ptsd-included-3.ris'
WARNING:root:[Errno 2] No such file or directory: 'https://raw.githubusercontent.com/asreview/systematic-review-datasets/master/datasets/van_de_Schoot_2017/raw/schoot-lgmm-ptsd-included-3.ris'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Bruin056/Documents/GitHub/asreview/asreview/data/base.py", line 51, in load_data
    return ASReviewData.from_file(name, *args, **kwargs)
  File "/Users/Bruin056/Documents/GitHub/asreview/asreview/data/base.py", line 187, in from_file
    df, column_spec = reader.read_data(fp)
  File "/Users/Bruin056/Documents/GitHub/asreview/asreview/io/ris_reader.py", line 140, in read_data
    raise ValueError("Cannot find proper encoding for data file.")
ValueError: Cannot find proper encoding for data file.
```

**Comment by J535D165** [comment]
Relevant code to extend with file downloader/streamer. 

https://github.com/asreview/asreview/blob/45b8600bfd3f11e7e92fe4fed387317ae546ceb4/asreview/io/ris_reader.py#L127-L140
