### ISSUE TITLE
Error launching ASReview Lab MacBook M1

### ISSUE THREAD

**Issue by MauerHaus** [asreview/asreview#1268]
**Describe the bug**
After installing ASReview when I try to launch the ASReview lab I am facing an error that the architecture incompatible.

**To Reproduce**
Steps to reproduce the problem: 
Try to launch the ASReview lab:
`asreview lab --port 5001
Traceback (most recent call last):
  File "/opt/homebrew/bin/asreview", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/asreview/__main__.py", line 78, in main
    entry.load()().execute(sys.argv[2:])
  File "/opt/homebrew/lib/python3.10/site-packages/asreview/entry_points/lab.py", line 91, in execute
    from asreview.webapp.start_flask import main
  File "/opt/homebrew/lib/python3.10/site-packages/asreview/webapp/start_flask.py", line 26, in <module>
    from gevent.pywsgi import WSGIServer
  File "/opt/homebrew/lib/python3.10/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/opt/homebrew/lib/python3.10/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/opt/homebrew/lib/python3.10/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so' (no such file), '/opt/homebrew/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

**Version information**
 - OS: MacBook Air M1 (2020), macOS Ventura 13.0.1
 - ASReview version 1.0.3
 - Homebrew 3.6.10
 - Python 3.10.8

**Additional context**
The Problem can be fixed with the following command:
`arch -arm64 pip install --no-binary gevent gevent`
I hope this helps others who also facing this kind of problem.

**Comment by J535D165** [comment]
Thanks for providing the fix as well! So far, we haven't seen issues with gevent. Most of the issues are related to sklearn. 

Related to #738.
