### ISSUE TITLE
No such file or directory: 'MarkupSafe-2.0.1.dist-info\\METADATA'

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#1513]
### Discussed in https://github.com/asreview/asreview/discussions/1512

<div type='discussions-op-text'>

<sup>Originally posted by **JohnQuentin** August 15, 2023</sup>
Hello, 

After several weeks of not using ASReview, I attempted to restart it this morning as I require some data for my project. Upon startup, I encountered the following notification, as depicted below. I have already attempted to update ASReview, which was successful. However, I am still encountering this error. Could someone provide further assistance in resolving this issue?

```
(base) C:\Users\johnv>asreview lab
2023-08-15 10:02:54.288858: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-08-15 10:02:54.289201: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3108, in _dep_map
    return self.__dep_map
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3099, in _parsed_pkg_info
    return self._pkg_info
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\johnv\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\johnv\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\johnv\anaconda3\Scripts\asreview.exe\__main__.py", line 7, in <module>
  File "C:\Users\johnv\anaconda3\lib\site-packages\asreview\__main__.py", line 48, in main
    entry.load()().execute(sys.argv[2:])
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2516, in load
    self.require(*args, **kwargs)
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2539, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 832, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2821, in requires
    dm = self._dep_map
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3110, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3119, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3101, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1517, in get_metadata
    value = self._get(path)
  File "C:\Users\johnv\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1726, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\johnv\\anaconda3\\lib\\site-packages\\MarkupSafe-2.0.1.dist-info\\METADATA'

(base) C:\Users\johnv>
```</div>

**Comment by J535D165** [comment]
Feel free to reopen or comment if this issue happens to you.
