### ISSUE TITLE
ASReview lab not working in new environment. 

### ISSUE THREAD

**Issue by DanielIAvila** [asreview/asreview#1533]
I have created a new environment with Anaconda Prompt for my review. The following are the packages installed by running `pip install asreview`

```
(review) C:\>pip list
Package              Version
-------------------- ------------
asreview             1.2
attrs                23.1.0
cattrs               23.1.2
certifi              2022.12.7
cffi                 1.15.1
charset-normalizer   3.3.0
click                8.1.7
colorama             0.4.6
datahugger           0.10.3
dill                 0.3.7
et-xmlfile           1.1.0
exceptiongroup       1.1.3
filelock             3.12.2
Flask                2.2.5
Flask-Cors           4.0.0
gevent               22.10.2
gitignorefile        1.1.2
greenlet             2.0.2
idna                 3.4
importlib-metadata   6.7.0
importlib-resources  5.12.0
itsdangerous         2.1.2
Jinja2               3.1.2
joblib               1.3.2
jsonpath-ng          1.6.0
jsonschema           4.17.3
MarkupSafe           2.1.3
natsort              8.4.0
numpy                1.21.6
openpyxl             3.1.2
pandas               1.3.5
pip                  22.3.1
pkgutil_resolve_name 1.3.10
platformdirs         3.10.0
ply                  3.11
pycparser            2.21
pyrsistent           0.19.3
python-dateutil      2.8.2
pytz                 2023.3.post1
requests             2.31.0
requests-cache       1.1.0
rispy                0.7.1
scikit-learn         1.0.2
scipy                1.7.3
scisort              0.5.3
scitree              0.5.3
seedir               0.4.2
setuptools           65.6.3
six                  1.16.0
threadpoolctl        3.1.0
tqdm                 4.66.1
typing_extensions    4.7.1
url-normalize        1.4.3
urllib3              2.0.5
Werkzeug             2.2.3
wheel                0.38.4
wincertstore         0.2
xlrd                 2.0.1
zipp                 3.15.0
zope.event           5.0
zope.interface       6.0

````

The error I am getting is

```
(review) C:\>asreview lab
Traceback (most recent call last):
  File "~\Anaconda3\envs\review\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "~\Anaconda3\envs\review\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~\Anaconda3\envs\review\Scripts\asreview.exe\__main__.py", line 4, in <module>
  File "~\Anaconda3\envs\review\lib\site-packages\asreview\__main__.py", line 18, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (~\Anaconda3\envs\review\lib\importlib\__init__.py)
```

**Comment by jteijema** [comment]
Hi @DanielIAvila !

This is a difficult error to debug for me! Let's try some things.

First of all, which python version are you using? You can find this by running `python -v` (or your systems alternative).

Second, what happens when you run `conda install -c anaconda importlib-metadata` and try again? This might help.

Let me know!
Jelle

**Comment by jteijema** [comment]
#1481 describes the same error, which was caused by python 3.7. I think I might be right about the versioning. Make sure you are using 3.8 or later for ASReview! 

Thank you for using the software,
JT

**Comment by Rensvandeschoot** [comment]
o great!
@DanielIAvila: can you maybe start a PR where exactly it would have helped for you to know this information (and refer to this issue?). This would be highly appreciated, especially since the ASReview project is a fully open-source and community-driven project. Many thanks!!

**Comment by jteijema** [comment]
#1479 bumps the minimum version in the documentation. I see that the documentation on stable is updated, but the latest branch of the docs isn't up to date. @J535D165 we should take a look at compile settings for read the docs.
