### ISSUE TITLE
ERROR:asreview.webapp.start_flask:Exception on / [GET]

### ISSUE THREAD

**Issue by wolfgangmeisen** [asreview/asreview#1597]
Dear All,
after Installation asreview wont start. 
Installation on: Microsoft Windows 10 22H2 with elevated rights. (see attached installation documentation)
 Ich found the follwing failure:
-----------------------------------------------------------
C:\Windows\system32>asreview lab
Start browser at http://localhost:5000/

If your browser doesn't open. Please navigate to 'http://localhost:5000/'

ERROR:asreview.webapp.start_flask:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\webapp\start_flask.py", line 434, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, t
[ASReview 1.3.2 Installationsanleitung.docx](https://github.com/asreview/asreview/files/13487938/ASReview.1.3.2.Installationsanleitung.docx)
[ASReview 1.3.2 Installationsanleitung.docx](https://github.com/asreview/asreview/files/13487941/ASReview.1.3.2.Installationsanleitung.docx)
[ASReview 1.3.2 Installationsanleitung.docx](https://github.com/asreview/asreview/files/13487945/ASReview.1.3.2.Installationsanleitung.docx)
emplate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.12\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
ERROR:root:index.html
127.0.0.1 - - [2023-11-28 11:34:53] "GET / HTTP/1.1" 500 152 0.014959

**Comment by wolfgangmeisen** [comment]
flask is as a webserver on port 5000 , isnt i? or is another webserver needed ?

**Comment by Rensvandeschoot** [comment]
What Python version are you running??

**Comment by Rensvandeschoot** [comment]
I found a similar error in this thread: https://github.com/asreview/asreview/issues/488#issuecomment-1599006234
with a solution in https://github.com/asreview/asreview/pull/491
not sure if this helps... 

How did you install ASReview, via pip?

**Comment by wolfgangmeisen** [comment]
#488: i saw it before and worked ist out.  not realy helpfull, cause there is no valuable information inside. (from my piont of view)
Ich guess, the templatre folder and the templates are not installed. But im not sure.

**Comment by wolfgangmeisen** [comment]
Hi J,
i'll check it out now.....

**Comment by J535D165** [comment]
Just uploaded and tested a new release: 1.3.4. The source distribution (tar.gz) works there as well. Thanks for reporting. Feel free to reopen the issue if you think it persists. 

```
% pip install asreview-1.3.4.tar.gz 
Processing ./asreview-1.3.4.tar.gz
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (1.26.1)
Requirement already satisfied: pandas<3,>=1 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (2.1.2)
Requirement already satisfied: scikit-learn in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (1.3.2)
Requirement already satisfied: rispy~=0.7.0 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (0.7.1)
Requirement already satisfied: xlrd>=1.0.0 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (2.0.1)
Requirement already satisfied: setuptools in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (68.2.2)
Requirement already satisfied: flask>=2.3.0 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (3.0.0)
Requirement already satisfied: flask_cors in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (4.0.0)
Requirement already satisfied: flask-login>=0.6.3 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (0.6.3)
Requirement already satisfied: flask-mail in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (0.9.1)
Requirement already satisfied: Werkzeug>=2.3.2 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (3.0.1)
Requirement already satisfied: openpyxl in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (3.1.2)
Requirement already satisfied: jsonschema in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (4.19.2)
Requirement already satisfied: filelock in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (3.13.1)
Requirement already satisfied: Flask-SQLAlchemy>=3.0.2 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (3.1.1)
Requirement already satisfied: requests in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (2.31.0)
Requirement already satisfied: tqdm in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (4.66.1)
Requirement already satisfied: gevent>=20 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (23.9.1)
Requirement already satisfied: datahugger>=0.2 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (0.10.4)
Requirement already satisfied: synergy_dataset in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (1.2)
Requirement already satisfied: sqlalchemy-utils in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from asreview==1.3.4) (0.41.1)
Requirement already satisfied: jsonpath-ng in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from datahugger>=0.2->asreview==1.3.4) (1.6.0)
Requirement already satisfied: requests-cache in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from datahugger>=0.2->asreview==1.3.4) (1.1.0)
Requirement already satisfied: scitree in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from datahugger>=0.2->asreview==1.3.4) (0.5.3)
Requirement already satisfied: Jinja2>=3.1.2 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from flask>=2.3.0->asreview==1.3.4) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from flask>=2.3.0->asreview==1.3.4) (2.1.2)
Requirement already satisfied: click>=8.1.3 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from flask>=2.3.0->asreview==1.3.4) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from flask>=2.3.0->asreview==1.3.4) (1.7.0)
Requirement already satisfied: sqlalchemy>=2.0.16 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from Flask-SQLAlchemy>=3.0.2->asreview==1.3.4) (2.0.23)
Requirement already satisfied: zope.event in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from gevent>=20->asreview==1.3.4) (5.0)
Requirement already satisfied: zope.interface in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from gevent>=20->asreview==1.3.4) (6.1)
Requirement already satisfied: greenlet>=3.0rc3 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from gevent>=20->asreview==1.3.4) (3.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from pandas<3,>=1->asreview==1.3.4) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from pandas<3,>=1->asreview==1.3.4) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from pandas<3,>=1->asreview==1.3.4) (2023.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from Werkzeug>=2.3.2->asreview==1.3.4) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from jsonschema->asreview==1.3.4) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from jsonschema->asreview==1.3.4) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from jsonschema->asreview==1.3.4) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from jsonschema->asreview==1.3.4) (0.10.6)
Requirement already satisfied: et-xmlfile in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from openpyxl->asreview==1.3.4) (1.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from requests->asreview==1.3.4) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from requests->asreview==1.3.4) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from requests->asreview==1.3.4) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from requests->asreview==1.3.4) (2023.7.22)
Requirement already satisfied: scipy>=1.5.0 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from scikit-learn->asreview==1.3.4) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from scikit-learn->asreview==1.3.4) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from scikit-learn->asreview==1.3.4) (3.2.0)
Requirement already satisfied: pyalex in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from synergy_dataset->asreview==1.3.4) (0.12)
Requirement already satisfied: tabulate in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from synergy_dataset->asreview==1.3.4) (0.9.0)
Requirement already satisfied: six>=1.5 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1->asreview==1.3.4) (1.16.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from sqlalchemy>=2.0.16->Flask-SQLAlchemy>=3.0.2->asreview==1.3.4) (4.8.0)
Requirement already satisfied: ply in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from jsonpath-ng->datahugger>=0.2->asreview==1.3.4) (3.11)
Requirement already satisfied: cattrs>=22.2 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from requests-cache->datahugger>=0.2->asreview==1.3.4) (23.1.2)
Requirement already satisfied: platformdirs>=2.5 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from requests-cache->datahugger>=0.2->asreview==1.3.4) (3.11.0)
Requirement already satisfied: url-normalize>=1.4 in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from requests-cache->datahugger>=0.2->asreview==1.3.4) (1.4.3)
Requirement already satisfied: gitignorefile in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from scitree->datahugger>=0.2->asreview==1.3.4) (1.1.2)
Requirement already satisfied: natsort in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from scitree->datahugger>=0.2->asreview==1.3.4) (8.4.0)
Requirement already satisfied: scisort in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from scitree->datahugger>=0.2->asreview==1.3.4) (0.5.3)
Requirement already satisfied: seedir in /Users/anon/.pyenv/versions/3.12.0/envs/asreview-prod/lib/python3.12/site-packages (from scitree->datahugger>=0.2->asreview==1.3.4) (0.4.2)
Building wheels for collected packages: asreview
  Building wheel for asreview (setup.py) ... done
  Created wheel for asreview: filename=asreview-1.3.4-py3-none-any.whl size=3297693 sha256=dc2a02129357c1bc28881749b0d599bc624e2ed2770783af03eab753f349a79e
  Stored in directory: /Users/Bruin056/Library/Caches/pip/wheels/a0/64/87/120420d26b91463b888d5b383d619c0930c4166cb000ab9e64
Successfully built asreview
Installing collected packages: asreview
Successfully installed asreview-1.3.4

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python3.12 -m pip install --upgrade pip
Bruin056@UU083226 Downloads % asreview lab
Start browser at http://localhost:5000/



If your browser doesn't open. Please navigate to 'http://localhost:5000/'




127.0.0.1 - - [2023-11-29 11:35:20] "GET / HTTP/1.1" 200 713 0.010319
127.0.0.1 - - [2023-11-29 11:35:20] "GET /static/css/main.9e747be3.css HTTP/1.1" 200 7688 0.001089
127.0.0.1 - - [2023-11-29 11:35:20] "GET /static/js/main.43c0da44.js HTTP/1.1" 200 1877818 0.026394
```

**Comment by wolfgangmeisen** [comment]
Thx in advance. Will check it.

**Comment by wolfgangmeisen** [comment]
Dear All,
1.)Update pip install --upgrade asreview1.3.4. tar.gz 
2.) It Works ! 
![image](https://github.com/asreview/asreview/assets/86890250/9313f195-8ceb-4646-9620-ce281944b143)
Thank You All very much for fast and reliable support!
