### ISSUE TITLE
Error install `asreview` (key: expected bytes or bytearray, but got 'NoneType')

### ISSUE THREAD

**Issue by aCampello** [asreview/asreview#1771]
**Describe the bug**
Error installing `asreview` server with poetry.

**To Reproduce**
Create an isolated environment with poetry. Add asreview. 
```
[tool.poetry]
name = "project-using-asreview"
version = "0.1.0"
description = ""
authors = ["Antonio Campello <a.campello@digital-science.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
asreview = "^1.6.2"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
ipython = "^8.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Run `asreview lab`. We hit the trace below
~                                           

**Screenshots**

**Version information**

- OS: Mac M2
- ASReview version [e.g. 0.6.2]: 1.6.2

**Additional context**

Here's the full trace

```bash
ERROR:asreview.webapp.app:Exception on / [GET]
Traceback (most recent call last):
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/asreview/webapp/app.py", line 148, in index
    return render_template("index.html", api_url=app.config.get("API_URL", "/"))
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask/templating.py", line 127, in _render
    app.update_template_context(context)
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask/app.py", line 493, in update_template_context
    context.update(self.ensure_sync(func)())
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask_login/utils.py", line 405, in _user_context_processor
    return dict(current_user=_get_user())
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask_login/login_manager.py", line 376, in _load_user
    user = self._load_user_from_remember_cookie(cookie)
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask_login/login_manager.py", line 414, in _load_user_from_remember_cookie
    user_id = decode_cookie(cookie)
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask_login/utils.py", line 62, in decode_cookie
    if hmac.compare_digest(_cookie_digest(payload, key=key), digest):
  File "/Users/acampello/Library/Caches/pypoetry/virtualenvs/review-pal--jkndWEG-py3.10/lib/python3.10/site-packages/flask_login/utils.py", line 380, in _cookie_digest
    return hmac.new(key, payload.encode("utf-8"), sha512).hexdigest()
  File "/Users/acampello/.pyenv/versions/3.10.4/lib/python3.10/hmac.py", line 184, in new
    return HMAC(key, msg, digestmod)
  File "/Users/acampello/.pyenv/versions/3.10.4/lib/python3.10/hmac.py", line 53, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'NoneType'
ERROR:root:key: expected bytes or bytearray, but got 'NoneType'
```

**Comment by aCampello** [comment]
Downgrading to 1.5.0 seems to fix the problem.

**Comment by J535D165** [comment]
Can you remove cookies? Did you experiment with auth/non-auth?

@cskaandorp
