### ISSUE TITLE
Problems installing ASReview

### ISSUE THREAD

**Issue by cjvanlissa** [asreview/asreview#182]
Installed ASreview as follows:

```
conda create -n veni_sysrev python=3.7.3
conda activate veni_sysrev
pip install git+https://github.com/asreview/asreview.git
```

Trying to run ASReview gave many errors about tensorflow. I ran this tensorflow selfcheck (https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c) and concluded that I needed to install CUDA, which I did. After that, I still get these errors:

```
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>
```

**Comment by cjvanlissa** [comment]
When separately installing tensorflow, as requested by @J535D165 , I get this:

Installing collected packages: tensorflow
Successfully installed tensorflow-2.1.0

```
(veni_sysrev) C:\Users\lissa102>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors
```

**Comment by J535D165** [comment]
@qubixes Can you have a look. Shall we make this dependency optional? Can you do this in the new release?

**Comment by qubixes** [comment]
@J535D165 Yes, I'll get it in for the next release.

@cjvanlissa Have you looked at: https://github.com/tensorflow/tensorflow/issues/22794? There seem to be a lot of people having the same problem. Perhaps the quickest fix you could try is to install an older version of tenosorflow:

`pip install "tensorflow<2.1"`

or

`pip install "tensorflow<2.0"`

or the cpu version of tensorflow:

`pip install tensorflow-cpu`

Might need to uninstall tensorflow in this case.

**Comment by cjvanlissa** [comment]
Thank you @qubixes , tensorflow now imports without error. Yes ASReview still doesn't work:

```
Installing collected packages: asreview
Successfully installed asreview-0.7.2

(veni_sysrev) C:\Users\lissa102>asreview oracle example_ptsd --state_file myreview.h5 --new

            _____ _____            _
     /\    / ____|  __ \          (_)
    /  \  | (___ | |__) |_____   ___  _____      __
   / /\ \  \___ \|  _  // _ \ \ / / |/ _ \ \ /\ / /
  / ____ \ ____) | | \ \  __/\ V /| |  __/\ V  V /
 /_/    \_\_____/|_|  \_\___| \_/ |_|\___| \_/\_/

---------------------------------------------------------------------------------
|                                                                                |
|  Welcome to the ASReview Automated Systematic Review software.                 |
|  In this mode the computer will assist you in creating your systematic review. |
|  After giving it a few papers that are either included or excluded,            |
|  it will compute a model and show progressively more relevant papers.          |
|                                                                                |
|  GitHub page:        https://github.com/asreview/asreview                      |
|  Questions/remarks:  asreview@uu.nl                                            |
|                                                                                |
---------------------------------------------------------------------------------

Traceback (most recent call last):
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lissa102\AppData\Local\Continuum\miniconda3\envs\veni_sysrev\Scripts\asreview.exe\__main__.py", line 7, in <module>
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\site-packages\asreview\__main__.py", line 48, in main
    entry.load()().execute(sys.argv[2:])
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\site-packages\asreview\entry_points\oracle.py", line 40, in execute
    review_oracle(path, **args_dict)
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\site-packages\asreview\review\factory.py", line 305, in review_oracle
    review(dataset, *args, mode='oracle', state_file=state_file, **kwargs)
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\site-packages\asreview\review\factory.py", line 237, in review
    reviewer = get_reviewer(*args, mode=mode, model=model, **kwargs)
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\site-packages\asreview\review\factory.py", line 116, in get_reviewer
    prior_dataset, new=new)
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\site-packages\asreview\review\factory.py", line 71, in create_as_data
    as_data.append(ASReviewData.from_file(data))
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\site-packages\asreview\data.py", line 197, in from_file
    if str(Path(fp).resolve()).endswith(suffix):
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\pathlib.py", line 1144, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "c:\users\lissa102\appdata\local\continuum\miniconda3\envs\veni_sysrev\lib\pathlib.py", line 201, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https:\\raw.githubusercontent.com\\asreview\\systematic-review-datasets\\master\\datasets\\Van_de_Schoot_PTSD\\output\\PTSD_VandeSchoot_18.csv'
```

**Comment by qubixes** [comment]
@cjvanlissa Thanks for reporting back. I can't reproduce the error myself, but I'll try and incorprate a fix for the new version.

For now, the issue seems with the path being an url, so if you want to work around the issue, you can download the original file to your home directory:

https://github.com/asreview/systematic-review-datasets/blob/master/datasets/Van_de_Schoot_PTSD/output/PTSD_VandeSchoot_18.csv

and use that filename instead of "example_ptsd".

**Comment by cjvanlissa** [comment]
OK, that works! Thank you

**Comment by J535D165** [comment]
Same issue for @Rensvandeschoot. Also on `import tensorflow` in standalone python console.

**Comment by J535D165** [comment]
https://github.com/tensorflow/tensorflow/issues/35749

**Comment by J535D165** [comment]
Confirmed. Downgrading TensorFlow works for Windows users. 

```
pip install --upgrade tensorflow=2.0
```

**Comment by Rensvandeschoot** [comment]
@J535D165 this has been solved in the newest release, right?

**Comment by J535D165** [comment]
Tensorflow is no longer a required dependency because Windows users might run into problems. The reported issue is a problem with tensorflow itself.
