### ISSUE TITLE
Unable to export Project file. unsupported operand type(s) for +: 'WindowsPath' and 'str'

### ISSUE THREAD

**Issue by Grapes178** [asreview/asreview#1879]
**Describe the bug**
I tried to export Project file of my partially reviewed project. It failed and displays the following message:

> unsupported operand type(s) for +: 'WindowsPath' and 'str' Please try again.

However, it successfully export my datasets without any issue. Including both full and relevant datasets in all formats.

**To Reproduce**
1. Go to Projects
2. Click "Export" on desired project
3. Select "Project" file
4. Click "Export"

**Screenshots**
n.a.

**Version information**

- OS: Microsoft Windows 10 Home Single Language
- Browser: Mozilla Firefox
- ASReview version: 1.6.3

**Additional context**

Here's the output from cmd
```plaintext
ERROR:asreview.webapp.app:Exception on /api/projects/4820717b801b45a0bfdfe96439c7ae87/export_project [GET]
Traceback (most recent call last):
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\asreview\webapp\authentication\decorators.py", line 40, in decorated_function
    return f(project, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\asreview\webapp\api\projects.py", line 1253, in export_project
    project.export(tmpfile)
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\asreview\project.py", line 653, in export
    shutil.make_archive(export_fp_tmp, "zip", root_dir=export_fp_tmp)
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\shutil.py", line 1130, in make_archive
    filename = func(base_name, base_dir, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.pyenv\pyenv-win\versions\3.11.0b4\Lib\shutil.py", line 977, in _make_zipfile
    zip_filename = base_name + ".zip"
                   ~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
ERROR:root:unsupported operand type(s) for +: 'WindowsPath' and 'str'

**Comment by J535D165** [comment]
Thanks for the detailed bug report. I haven't seen this before, strangely. 

I think `shutil.make_archive(export_fp_tmp, "zip", root_dir=export_fp_tmp)` should be able to handle Path objects?

Can a Windows user with 1.6.3 reproduce this issue? @Rensvandeschoot @PeterLombaers @VeenDuco

**Comment by PeterLombaers** [comment]
I tried to reproduce, but for me the export worked fine.

**Versions**
- Windows 10
- Python: 3.11
- ASReview 1.6.3
- Browser: Chrome

**Comment by J535D165** [comment]
@Grapes178 Your Python version most likely causes the issue. You are using a release candidate with a bug. Please use ASReview with a stable Python version, preferably the latest update. 

See https://github.com/python/cpython/issues/94844 for more details about the bug.
