### ISSUE TITLE
Error when searching Hall dataset

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#209]
The dataset Hall results in a freeze on the search step because of an error in the backend. 

```
127.0.0.1 - - [02/Apr/2020 09:58:42] "POST /api/project/lkjdfglkjdfhlkj/upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Apr/2020 09:58:42] "POST /api/project/lkjdfglkjdfhlkj/upload HTTP/1.1" 200 -
127.0.0.1 - - [02/Apr/2020 09:58:49] "GET /api/project/lkjdfglkjdfhlkj/search?q=software&n_max=10 HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [02/Apr/2020 09:58:49] "GET /api/project/lkjdfglkjdfhlkj/search?q=software&n_max=10 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jonathan/Dropbox/UU_Projects/UU_ASReview/asreview/asreview/webapp/api.py", line 219, in api_search_data
    result_search = search_data(project_id, q=q, n_max=max_results)
  File "/Users/jonathan/Dropbox/UU_Projects/UU_ASReview/asreview/asreview/webapp/utils/datasets.py", line 14, in search_data
    paper_ids = as_data.fuzzy_find(q, max_return=n_max, exclude=[])
  File "/Users/jonathan/Dropbox/UU_Projects/UU_ASReview/asreview/asreview/data.py", line 355, in fuzzy_find
    new_ranking = get_fuzzy_scores(keywords, match_str)
  File "/Users/jonathan/Dropbox/UU_Projects/UU_ASReview/asreview/asreview/data.py", line 93, in get_fuzzy_scores
    return token_set_ratio(keywords, str_list)
  File "/Users/jonathan/Dropbox/UU_Projects/UU_ASReview/asreview/asreview/data.py", line 75, in token_set_ratio
    return match_best(keywords, inv_index, n_match=len(inv_index))
  File "/Users/jonathan/Dropbox/UU_Projects/UU_ASReview/asreview/asreview/data.py", line 68, in match_best
    ratios[idx] += rat
IndexError: index 7907 is out of bounds for axis 0 with size 7889
```

**Comment by J535D165** [comment]
@qubixes Can you fix this one?
