### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by rupertoverall** [asreview/asreview#273]
**Describe the bug**
*What happened? And what did you expect to happen?*
When creating a new project, clicking on the plugins tab fails with the error:
```
ERROR:asreview.webapp.start_flask:Exception on /api/datasets [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
```

**To Reproduce**
Steps to reproduce the problem: Run `asreview oracle`, open new project, click on the plugins tab.

**Screenshots**

**Version information**
 - OS: OS X 10.14.6
 - ASReview version 0.9.6
 - asreview-covid19 version 0.9.1

**Additional context**
Run on python 3.8

**Comment by J535D165** [comment]
Thanks for reporting. 

Can you have a look at https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org.  It might be an issue with you Python installation and certificates on MacOS.

**Comment by rupertoverall** [comment]
Oh wow - that was an easy fix!
After running 'Install Certificates.command', the plugin is loading correctly. Thanks for the quick response.

**Comment by ganesh2405** [comment]
Hi Can someone help me with same issue on Windows, aslo using corporate environment
