### ISSUE TITLE
Running same simulation twice in a row fails

### ISSUE THREAD

**Issue by behrica** [asreview/asreview#288]
**Describe the bug**
Running the same simulation and writing the state file, fails on the second run. This seems to be related to the fact, that the stage file exists already.

This seems to be a strange behaviour.
```
asreview simulate -s 1.json  1.csv
asreview simulate -s 1.json  1.csv 
```

fails with generic error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/asreview", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/asreview/__main__.py", line 40, in main
    entry.load()().execute(sys.argv[2:])
  File "/usr/local/lib/python3.6/site-packages/asreview/entry_points/simulate.py", line 29, in execute
    review_simulate(path, **args_dict)
  File "/usr/local/lib/python3.6/site-packages/asreview/review/factory.py", line 239, in review_simulate
    review(dataset, *args, mode='simulate', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/asreview/review/factory.py", line 222, in review
    reviewer = get_reviewer(*args, mode=mode, model=model, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/asreview/review/factory.py", line 197, in get_reviewer
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/asreview/review/simulate.py", line 49, in __init__
    if len(start_idx) == 0 and n_prior_included + n_prior_excluded > 0:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

**Comment by J535D165** [comment]
Thanks for figuring out. An informative error message would be better. Are you interested in doing a PR?

**Comment by qubixes** [comment]
@J535D165 I don't want to be rude, but I should probably fix it...

**Comment by qubixes** [comment]
With the above pull request it should not fail anymore. (It will try to continue the simulation, and if it is already done it will immediately quit.)

**Comment by J535D165** [comment]
Thanks for fix and thansk for reporting @behrica

**Comment by behrica** [comment]
> With the above pull request it should not fail anymore. (It will try to continue the simulation, and if it is already done it will immediately quit.)

 Is the "concept" of "continuing the simulation" documented somewhere ?
It is not obvoius to me, why and how I should start a simulation and later "continue with it".

Probbaly it comes from the fact that the for the "oracle" mode, this makes sense, and somehow the "simulation" is similar to the "oracle", correct ?
