### ISSUE TITLE
Error message KeyError: 'record_id 407639 not found in data.'

### ISSUE THREAD

**Issue by franzbischoff** [asreview/asreview#542]
An error occurred. Please send an email to asreview@uu.nl or file an issue on GitHub.

Error message
KeyError: 'record_id 407639 not found in data.'

Ubuntu 20.04 LTS on WSL2
last version of ASReview as today: 0.16

Log:
```
ERROR:root:Project covid-19 - KeyError: 'record_id 407639 not found in data.'
Traceback (most recent call last):
  File "/home/franz/.local/lib/python3.8/site-packages/asreview/compat.py", line 24, in convert_id_to_idx
    result.append(inv_record_id[i])
KeyError: 407639

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/franz/.local/lib/python3.8/site-packages/asreview/__main__.py", line 122, in <module>
    main()
  File "/home/franz/.local/lib/python3.8/site-packages/asreview/__main__.py", line 80, in main
    entry.load()().execute(sys.argv[2:])
  File "/home/franz/.local/lib/python3.8/site-packages/asreview/entry_points/lab.py", line 83, in execute
    main_run_model(argv)
  File "/home/franz/.local/lib/python3.8/site-packages/asreview/webapp/run_model.py", line 194, in main
    raise err
  File "/home/franz/.local/lib/python3.8/site-packages/asreview/webapp/run_model.py", line 180, in main
    train_model(args.project_id, args.label_method)
  File "/home/franz/.local/lib/python3.8/site-packages/asreview/webapp/run_model.py", line 155, in train_model
    current_pool_idx = convert_id_to_idx(as_data, current_pool)
  File "/home/franz/.local/lib/python3.8/site-packages/asreview/compat.py", line 26, in convert_id_to_idx
    raise KeyError(f"record_id {i} not found in data.")
KeyError: 'record_id 407639 not found in data.'
ERROR:root:error on training
INFO:werkzeug:127.0.0.1 - - [03/Apr/2021 01:14:03] "GET /api/project/covid-19/model/init_ready HTTP/1.1" 400 -
```

**Comment by J535D165** [comment]
Hi @franzbischoff can you explain when/where this error was reported? 

If possible, export your project file and send it to us. I will inspect the file.

**Comment by franzbischoff** [comment]
This error occurs before I start screening (during the first model
creation).

I imported all three datasets of covid-19 and I filtered as "relevant" some
articles about early prophylaxis.

--
Francisco Bischoff

**Comment by SagevdBrand** [comment]
Hey there @franzbischoff , thanks for reporting the bug! 
 
What might have happened is that with loading the dataset, multiple datasets have overlapped each other! We'll look into how we can prevent this for future 😊 

Could you check which version of the CORD-19 plugin you have? Or simply install the latest version with `pip install asreview-covid19`?

If possible, create a new project and only use/click on one of the cord-datasets. It takes a while for some of them to load, because they're so large. If you want to use the other datasets as well, they would have to be in separate projects. 

I hope this helps! Please let us know whether this worked 💪

**Comment by franzbischoff** [comment]
I use the last of last... and I've imported all databases... so they might
be overlapped...
--
Francisco Bischoff

**Comment by SagevdBrand** [comment]
Ah that might explain the issue indeed then. Thank you for checking.
Could you let us know whether your problem was solved?

All the best,
Sofie
