### ISSUE TITLE
Ubuntu on windows10 COVID database error not found

### ISSUE THREAD

**Issue by hherce** [asreview/asreview#849]
Installed the covid database using: pip install asreview-covid19
and after running: asreview lab
making a new project I get the following error when I click on any of the two datasets plugins for covid.

Traceback (most recent call last):
  File "/home/hherce/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hherce/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hherce/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/hherce/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hherce/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/hherce/.local/lib/python3.8/site-packages/asreview/webapp/api.py", line 308, in api_upload_data_to_project
    plugin_data = DatasetManager().find(request.form['plugin'])
  File "/home/hherce/.local/lib/python3.8/site-packages/asreview/datasets.py", line 301, in find
    raise DataSetNotFoundError(
asreview.datasets.DataSetNotFoundError: Dataset undefined not found
ERROR:root:Dataset undefined not found

**Comment by Rensvandeschoot** [comment]
@hherce what version of asreview and plugin did you use?

**Comment by terrymyc** [comment]
Hi @hherce, thanks for reaching out. This issue will be fixed in the upcoming 0.19 release.
