### ISSUE TITLE
SBert feature extractor depends on a depricated transformer

### ISSUE THREAD

**Issue by JTeijema** [asreview/asreview#874]
**Describe the bug**
When selecting the SBert feature extractor, the following error arises:

```
Traceback (most recent call last):
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\review\base.py", line 201, in __init__
    self.X = state.get_feature_matrix(as_data.hash())
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\state\dict.py", line 125, in get_feature_matrix
    my_data = self._state_dict["data_properties"][data_hash]
KeyError: 'data_properties'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\Scripts\asreview.exe\__main__.py", line 7, in <module>
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\__main__.py", line 80, in main
    entry.load()().execute(sys.argv[2:])
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\entry_points\simulate.py", line 48, in execute
    review_simulate(path, **args_dict)
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\review\factory.py", line 314, in review_simulate
    review(dataset, *args, mode='simulate', **kwargs)
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\review\factory.py", line 268, in review
    reviewer = get_reviewer(*args, mode=mode, model=model, **kwargs)
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\review\factory.py", line 229, in get_reviewer
    reviewer = ReviewSimulate(as_data,
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\review\simulate.py", line 100, in __init__
    super(ReviewSimulate, self).__init__(as_data,
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\review\base.py", line 203, in __init__
    self.X = feature_model.fit_transform(as_data.texts,
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\models\feature_extraction\base.py", line 55, in fit_transform
    X = self.transform(texts)
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\asreview\models\feature_extraction\sbert.py", line 56, in transform
    model = SentenceTransformer('bert-base-nli-mean-tokens')
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 80, in __init__
    snapshot_download(model_name_or_path,
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\sentence_transformers\util.py", line 454, in snapshot_download
    path = cached_download(
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\huggingface_hub\file_download.py", line 351, in cached_download
    r.raise_for_status()
  File "C:\Users\5927226\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/sentence-transformers/bert-base-nli-mean-tokens/resolve/940b797366fedff0e361664b655910c1d37edf76/.gitattributes
```

To my knowledge, this is caused by the use of a [deprecated transformer](https://huggingface.co/sentence-transformers/bert-base-nli-mean-tokens) in [sbert.py](https://github.com/asreview/asreview/blob/master/asreview/models/feature_extraction/sbert.py)

**Version information**
 - OS: Windows
 - ASReview version 0.18

**Comment by J535D165** [comment]
Interested in doing a PR? What model do you think is the best replacement? 

Besides that, we can replace the hard coded model by an argument immediately.

**Comment by JTeijema** [comment]
I ran some simulations using `all-mpnet-base-v2`, `multi-qa-mpnet-base-dot-v1` and `all-distilroberta-v1`, a generalized model, a question/answer model and a small model. I'll post the results as soon as they're done.

Moreover, running this from an argument line would be perfect, as there's also a selection of Multi-Lingual Models available, like `distiluse-base-multilingual-cased-v1`.

**Comment by JTeijema** [comment]
An overview is available here: https://www.sbert.net/docs/pretrained_models.html

**Comment by JTeijema** [comment]
![output](https://user-images.githubusercontent.com/28191416/145072273-2ff4d794-300d-4e7d-b008-40e8a7811c5d.png)

Some runs show these results, together with the runtime being quicker or slower by a factor of the model size. (`all-distilroberta-v1` being the smallest model, runs the fastest, and `multi-qa-mpnet-base-dot-v1` the slowest)

From these results I would advice against a QA model, and opt for the generalized `all-mpnet-base-v2`model.

I've also tested the MSMARCO Passage Models but they performed even worse.

**Comment by Rensvandeschoot** [comment]
Closed with https://github.com/asreview/asreview/pull/878
