### ISSUE TITLE
ASReview 0.19 RIS export error: "float object is not iterable"

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#992]
### Discussed in https://github.com/asreview/asreview/discussions/988

<div type='discussions-op-text'>

<sup>Originally posted by **jaohls** February 22, 2022</sup>
Hi there all you excellent ASReview people,

Stumbled upon this problem - a colleague in my team cannot export to RIS file after screening ~25 % of the data.
![image](https://user-images.githubusercontent.com/96236396/155088009-363610db-f3d7-4252-a0dc-9e9088b1ef1b.png)

Export to CSV and Excel formats seem to work.

Uploaded the .asreview project file in question here: https://drive.protonmail.com/urls/NTB1H2V6QG#tQ68AB753Apx
</div>

Steps to reproduce the issue: 

```
from asreview import ASReviewData

asr_data = ASReviewData.from_file("Ny_uten_dupl_MR_Eksport.txt").to_ris("test_export.ris")
```
Output
```
Type "help", "copyright", "credits" or "license" for more information.
>>> from asreview import ASReviewData
>>> 
>>> asr_data = ASReviewData.from_file("Ny_uten_dupl_MR_Eksport.txt").to_ris("test_export.ris")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/Documents/GitHub/asreview/asreview/data/base.py", line 489, in to_ris
    return write_ris(df, fp)
  File "/Users/xxx/Documents/GitHub/asreview/asreview/io/ris_writer.py", line 102, in write_ris
    rispy.dump(records_new, fp)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/rispy/writer.py", line 185, in dump
    text = dumps(references, implementation=implementation, **kw)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/rispy/writer.py", line 208, in dumps
    return writer(**kw).formats(references)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/rispy/writer.py", line 145, in formats
    return "\n".join(lines)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/rispy/writer.py", line 138, in _format_all_references
    lines_ref = self._format_reference(ref, count=i + 1)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/rispy/writer.py", line 123, in _format_reference
    for val_i in value:
TypeError: 'float' object is not iterable
```

It looks to me like there is a `np.nan` send to `rispy`, however it should be `None`. @ottomattas

**Comment by J535D165** [comment]
Example of what is passed to rispy

```
{'abstract': 'Background Logic and experience suggest that it is easier in '
              'some situations than in others to change behaviour and '
              "organisation to improve patient safety. Knowing which 'context "
              "factors' help and hinder implementation of different changes "
              'would help implementers, as well as managers, policy makers, '
              'regulators and purchasers of healthcare. It could help to judge '
              'the likely success of possible improvements, given the '
              'conditions that they have, and to decide which of these '
              'conditions could be modified to make implementation more '
              'effective. Methods The study presented in this paper examined '
              'research to discover any evidence reported about whether or how '
              'context factors influence the effectiveness of five patient '
              'safety interventions. Results The review found that, for these '
              'five diverse interventions, there was little strong evidence of '
              'the influence of different context factors. However, the '
              'research was not designed to investigate context influence. '
              'Conclusions The paper suggests that significant gaps in '
              'research exist and makes proposals for future research better '
              'to inform decision-making.',
  'accession_number': 'rayyan-264553546',
  'alternate_title1': nan,
  'author_address': nan,
  'authors': ['Øvretveit, John C.',
              'Shekelle, Paul G.',
              'Dy, Sydney M.',
              'McDonald, Kathryn M.',
              'Hempel, Susanne',
              'Pronovost, Peter',
              'Rubenstein, Lisa',
              'Taylor, Stephanie L.',
              'Foy, Robbie',
              'Wachter, Robert M.'],
  'custom2': nan,
  'date': nan,
  'doi': nan,
  'edition': nan,
  'id': '1022',
  'included': nan,
  'issn': '2044-5415',
  'keywords': ['Environment',
               'Classification',
               'Patient Safety',
               'Program Implementation',
               'Methods',
               'Quality Improvement',
               'Research Priorities',
               'Accidental Falls',
               'Prevention and Control',
               'Behavioral Changes',
               'Guideline Adherence',
               'Health Facility Environment',
               'Leadership',
               'Medication Reconciliation',
               'Organizational Culture',
               'Research Design'],
  'language': nan,
  'notes': ['tables/charts. Journal Subset: Blind Peer Reviewed; Europe; '
            'Expert Peer Reviewed; Health Services Administration; Peer '
            'Reviewed; UK & Ireland. NLM UID: 101546984. PMID: NLM21493589.',
            'ASReview_not_seen'],
  'number': '7',
  'original_publication': nan,
  'place_published': nan,
  'publisher': nan,
  'secondary_authors': nan,
  'secondary_title': 'BMJ Quality & Safety',
  'short_title': 'How does context affect interventions to improve patient '
                 'safety? An assessment of evidence from studies of five '
                 'patient safety practices and proposals for research',
  'start_page': '604-610',
  'subsidiary_authors': nan,
  'title': 'How does context affect interventions to improve patient safety? '
           'An assessment of evidence from studies of five patient safety '
           'practices and proposals for research',
  'type_of_reference': 'JOUR',
  'url': 'https://www.ncbi.nlm.nih.gov/pubmed/21493589',
  'volume': '20',
  'year': '2011'}
```
